name: 'ga-model-deployment'
description: 'Launch Metaflow model deployment worflow & Launch Loki tests'
outputs:
  results: # id of output
    description: 'Results of the model prediction regression workflow'
  success:
    description: 'Does Loki integration has succeed or not'
  threadTS:
    description: 'Run Slack threadTS'
inputs:
  lokiSkip:
    description: 'Skips Loki ArgoWorkflow.'
    required: true
    default: "0"
  workflowTemplateName:
    description: 'Name of the Argo Workflow template to run'
    required: false
    default: 'workflowtemplate/wt-model-deploy-non-regression'
runs:
  using: 'composite'
  steps:
    - id: build
      run: docker build . --build-arg PYPI_USERNAME=$PYPI_USERNAME --build-arg PYPI_PASSWORD=$PYPI_PASSWORD -t action:latest
      shell: bash
    - id: run
      run: docker run --rm -v $(pwd):/github/workspace --workdir /github/workspace action:latest
      shell: bash