name: 'ga-model-deployment'
description: 'Launch Metaflow model deployment worflow & Launch Loki tests'
inputs:
  modelInstanceId:
    description: 'generated modelInstanceId given by previous registerModel in bookish-happiness'
    required: true
  argoServer:
    description: 'Host of the Argo server to trigger the worflow'
    required: false
    default: 'argo.inarix.com'
  workflowTemplateName:
    description: 'Name of the Argo Workflow template to run'
    required: false
    default: 'workflowtemplate/wt-model-deploy-non-regression'
outputs:
  results: # id of output
    description: 'Results of the model prediction regression workflow'
  success:
    description: 'Does Loki integration has succeed or not'
runs:
  using: 'docker'
  image: 'Dockerfile'
