name: 'ga-model-deployment'
description: 'Launch Metaflow model deployment worflow & Launch Loki tests'
inputs:
  skipDeployment:
    description: 'Skips metaflow ArgoWorkflow for model deployment and API registration'
    required: true
    default: "0"
  modelInstanceId:
    description: 'generated modelInstanceId given by previous registerModel in bookish-happiness'
    required: false
  workflowTemplateName:
    description: 'Name of the Argo Workflow template to run'
    required: false
    default: 'workflowtemplate/wt-model-deploy-non-regression'
outputs:
  results: # id of output
    description: 'Results of the model prediction regression workflow'
  success:
    description: 'Does Loki integration has succeed or not'
  threadTS:
    description: 'Run Slack threadTS'
runs:
  using: 'docker'
  image: 'Dockerfile'
