name: 'ga-model-deployment'
description: 'Launch Metaflow model deployment worflow & Launch Loki tests'
outputs:
  results: # id of output
    description: 'Results of the model prediction regression workflow'
  success:
    description: 'Does Loki integration has succeed or not'
  threadTS:
    description: 'Run Slack threadTS'
  modelInstanceId:
    description: 'ModelInstance id registered by the API'
inputs:
  lokiSkip:
    description: 'Skips Loki ArgoWorkflow.'
    required: true
    default: "0"
  workflowTemplateName:
    description: 'Name of the Argo Workflow template to run'
    required: false
    default: 'workflowtemplate/wt-model-deploy-non-regression'
  pypiUsername:
    description: 'Username for inarix pypiserver'
    required: true
  pypiPassword:
    description: 'Password for inarix pypiserver'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pypiUsername }}
    - ${{ inputs.pypiPassword }}
