name: 'ga-model-deployment'
description: 'Launch Metaflow model deployment worflow & Launch Loki tests'
inputs:
  lokiSkip:
    description: 'Skips Loki ArgoWorkflow.'
    required: true
    default: "0"
  workflowTemplateName:
    description: 'Name of the Argo Workflow template to run'
    required: false
    default: 'workflowtemplate/wt-model-deploy-non-regression'
outputs:
  results: # id of output
    description: 'Results of the model prediction regression workflow'
  success:
    description: 'Does Loki integration has succeed or not'
  threadTS:
    description: 'Run Slack threadTS'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ secrets.PYPI_USERNAME }}
    - ${{ secrets.PYPI_PASSWORD }}
